### ISSUE TITLE
Question: UI: Fti status bar: Could not estimate error-bars.  

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#14]
Sometimes after the refitting, the fit parameters are no longer changed (so best fit), but this causes a warning for example:
  In terminal:
      ```##  Warning: uncertainties could not be estimated:
    pg_c0:                  at initial value
      ``` 
  In UI:
      In "Fit status" "Message" : 
         ```
          Fit succeeded. Could not estimate error-bars.
         ```
Which error-bars are we talking about here?

**Comment by Julian-Hochhaus** [comment]
It's a warning from lmfit. If one of your parameters stays at its initial value, eg. you start with pg_c0=0 and lmfit reaches no improvement of the fit by variating this parameter, pg_c0 is left at its initial value. Therefore, the fit succeeded without the variation of all free parameters. That's a clear indication that your fit was successful and you can now keep these "initial value"-parameters fixed if you wish to fit further (and optimize the remaining parameters). 
During the optimization, lmfit tries to determine confidence intervals for each parameter (the fitting error is given in the fitting report in the terminal during execution or after export in the _fit.txt as parameter=value +/- error (xx%) ). If your parameter was not variated during fitting, these confidence intervals could not be calculated. These are the error bars that are meant.

[The ModelResult() class in lmfit actually offers the opportunity to calculate the uncertainty of a fit and plot it](https://lmfit.github.io/lmfit-py/model.html#calculating-uncertainties-in-the-model-function), I haven't implemented such functionality to LG4X-V2 because the plot gets messy if one displays all uncertainty intervals in addition to the fitted components.

**Comment by Hexanders** [comment]
Nice, thanks for the very detailed explanation. 
here just a thought: It could help in many cases to look at the uncertainties. My opinion is that [plotly](https://plotly.com/python/) could do a good job for this, because you could turn off the unwanted things by clicking on legend. The only question is whether it could be implemented well in the UI.
