### ISSUE TITLE
QTableWidget: cannot insert an item that is already owned by another QTableWidget

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#4]
Crash after trying to fit the data with Tougaard.
LG4X window becomes unresponsive

Data: 
    kinetic energy range: [7.5,14.5] eV
    two peaks at about 9 eV and 12 eV
Fit:
    Two peaks at ca 6 and 12 eV (both with the "gds" peak profile).
    Background: Polinomial and Tougaard

First warning:
```
Max iterations exceeded before convergence.
~.local/lib/python3.10/site-packages/lmfit/model.py:990: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " +

```

Then error:
 
```
QTableWidget: cannot insert an item that is already owned by another QTableWidget
~/LG4X-V2/Python/main.py:2050: RuntimeWarning: invalid value encountered in divide
  y_temp = y_area / np.max(y_area)
Traceback (most recent call last):
  File "~/LG4X-V2/Python/main.py", line 1103, in fit
    self.ana('fit')
  File "~/LG4X-V2/Python/main.py", line 2052, in ana
    fwhm_temp = x_[-1] - x_[0]
IndexError: list index out of range

```

**Comment by Julian-Hochhaus** [comment]
Thanks for reporting!
The error here is truly an invalid value in the calculation of the fwhm's, the other two messages are just warnings. I therefore divided the topic into two issues (invalid value in true divide  #9 and QTableWidget in #8 ).

The first warning
```
~.local/lib/python3.10/site-packages/lmfit/model.py:990: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " +
```
is caused by an outdated version of lmfit.

In the current stable version of lmfit using two independent variables in the fit model is not possible, but that's necessary to include the Tougaard and Shirley background into the fit procedure. Therefore, one needs to install the [development version of lmfit](https://lmfit.github.io/lmfit-py/installation.html) which allows the use of different independent variables in the fit model.
To use the development version of lmfit, its the easiest to remove the i.e. via pip installed version of lmfit first and afterwards install the development version of lmfit.

In a future version, I will first check the version of lmfit, so that the user gets a dedicated warning if an outdated version of lmfit is used.

**Comment by Julian-Hochhaus** [comment]
Coming back to the warning:
```
~.local/lib/python3.10/site-packages/lmfit/model.py:990: UserWarning: The keyword argument y does not match any arguments of the model function. It will be ignored.
  warnings.warn(f"The keyword argument {name} does not " +
```
Additionally, this warning is thrown, if the tougaard background is used in Evaluation mode or in the fit without the active background parameter. This causes no harm, because then `y` (the intensity) is passed to the model before evaluation only without the ability to be used as an independent variable.

This needs to be made more clear to the user in future versions.

**Comment by Julian-Hochhaus** [comment]
Moved to #10
