### ISSUE TITLE
Add option to name peaks and peak legend in Matplotlib

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#51]
Hi,
This is a feature request.
Add an option to name peaks other than C_1, C_2, etc.
This should also change the legend shown in the plot.
I think this would be useful as part of exporting the XPS image from Matplotlib.

**Comment by Julian-Hochhaus** [comment]
Great idea! Due to the headers of QtTableWidget not being editable, I subclassed QtTableWidget.

However, I was not able to make the labels editable directly, but had to make a small edit-dialog which opens after double clicking the table header and enables the user to change the column header.

Enhancement is introduced on dev branch already!

**Comment by kevinsmia1939** [comment]
Hi, I test it. It works. Thanks.
