### ISSUE TITLE
Amplitude and approx.area_p1

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#54]
Hi,

From the documentation, the amplitude correspond to the peak area. So I wonder what approx.area_p1 mean in this?
I expect it to have the same ratio, if it is the same thing but the ratio is different.

221747+39852+41402
= 303001
![Screenshot_20230519_145610](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/efabb68b-c959-4717-919e-8d40e8fa05f6)

39852/303001
= 0.13

22419+2482+2849
= 27750

2482/27750
= 0.089

Thanks.

**Comment by Julian-Hochhaus** [comment]
Sorry, the confusion is probably caused because I haven't had time to update the documentation yet and the documentation still refers to the work of [Hideki Nakajima on LG4X](https://github.com/hidecode221b/LG4X). 
I have redefined the models so that the amplitude represents the intensity value at the maximum value of a peak.
The approx. area meanwhile is the integrated area for each peak using Simpsons rule. This is always only an approximation because, for models with asymmetry, the area is not well-defined and infinite. I do only calculate the area for each component in the measurement window.

In your case, the lorentzian differs between both components. Therefore, ratio of areas and amplitudes of the peaks greatly differ.
