### ISSUE TITLE
[Enhancement] Add a constraint or ratio for peak area.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#65]
Hi,

I found that peaks from spin orbit splitting can have a fixed area ratio.
From this paper: https://doi.org/10.1116/6.0000377

For example, the area of the subshell p1/2:p3/2 ratio is 1:2.
So I think it will be useful to add ratio constraints to area as well.

![Screenshot_20230531_132427](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/65479a86-0ff7-4984-a840-51caa62da2b6)

What do you think?

**Comment by Julian-Hochhaus** [comment]
That's possible, but only for symmetric peaks.
For asymmetric peaks, the area is infinite and not well defined. It is therefore not easily possible to set constraints to the area for all models. In addition, keep in mind that the area ratio calculated using the j value is only an approximation. 
You need to use the actual cross section for calculating area ratios: [Yeh&Lindau](https://www.sciencedirect.com/science/article/pii/0092640X85900166)

However, I will think about it in the future.

**Comment by Julian-Hochhaus** [comment]
I will not implement the feature for now as it would only lead to further issues due to asymmetric peaks.

One possible approach to implementation would be to use the area instead of the amplitude as a scaling parameter for the peak function. The effort required for this would actually not be too significant; one would only need to modify all the peak models accordingly. However, I am somewhat hesitant to do this because asymmetric peaks would then introduce certain problems due to the indefinite area in the measurement range. If constraints were applied to asymmetric peaks, they would always depend on the integration interval and thus on the selected fitting range. I find that challenging.
