### ISSUE TITLE
Skewed Voigh seems to report a wrong peak position.

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#93]
Hi,

I use the latest commit: 0e11a6d3be387c488b5c738bee5af6c9e8a2938b

When using skewed Voigh with a high skew value, like 1, for example, The peak position on the plot does not seem to match what is shown in the "center" value. Is this normal?
Here, I set the center to 285 eV, but I can see in the plot that it is about 285.5 eV.

![Screenshot_20230928_104326](https://github.com/Julian-Hochhaus/LG4X-V2/assets/11407922/2c8e1c1a-0d13-4847-81af-ba83e7feec8b)

**Comment by kevinsmia1939** [comment]
It's possible that the peak location was derived from the mean or median rather than the mode, which is the highest point.

**Comment by Julian-Hochhaus** [comment]
It’s actually the expected behavior. The center value given is indeed the value fed to the skewed voigt formula. However, the skew shifts the maximum of the peak away from the center.


![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Skew_normal_densities.svg/2560px-Skew_normal_densities.svg.png)

[Wikipedia](https://en.wikipedia.org/wiki/Skew_normal_distribution)

**Comment by kevinsmia1939** [comment]
Thanks for clarification!
